org: danthe42
app: serverless-review-app
service: serverless-review-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs16.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

  tracing:
    lambda: true
    apiGateway: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*' 
    - Effect: Allow
      Action:
        - 'logs:PutLogEvents'
        - 'logs:CreateLogStream'
        - 'logs:CreateLogGroup'
      Resource:
      - '*'  

